### PR TITLE
Feature/proposal

### PR DESCRIPTION
**Pull request by cwefso**
### Type of change made:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Styling- no new features

### Detailed Description
This deploys our front end application and mocks out our ballot initiative steps

### Why is this change required? What problem does it solve?
Deploys front end to heroku

### CODE REVIEW

**Review by Rostammahabadi — APPROVED** [review]
Not sure what was changed as there's 3mil lines of code deleted and 15k added but from your description, it sounds good!

**Comment by muydanny** [comment]
Hey man I worked hard for that 3 million lines of code

**Comment by cwefso** [comment]
Haha, yeah that's what happens when you keep having to clear your node_modules and reinstalling everything so heroku will let you deploy

**Review by Aeickelman40 — APPROVED** [review]
HUGE! Thanks for adding the styling getting a template going for the step process. You da man!

**Pull request merged**
